---
# tasks file for post-install

- debug:
    msg: " The dbname is {{dbname}}"

- debug:
    var: dbuser

- name: Install mariadb-server
  ansible.builtin.yum:
    name: mariadb-server
    state: present

- name: Install PyMySQL
  ansible.builtin.yum:
    name: python3-PyMySQL
    state: present

- name: Start and Enable service
  ansible.builtin.service:
    name: mariadb
    state: started 
    enabled: yes

- name: Create a new database
  community.mysql.mysql_db:
    name: "{{dbname}}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create database user
  community.mysql.mysql_user:
    name: "{{dbuser}}"
    password: "{{dbpass}}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  register: dbout

- name: print dbout var
  debug:
    var: dbout

- name: create user
  ansible.builtin.user:
    name: "{{USER}}"
    comment: "{{COMM}}"
   
  register: usrout

- debug:
     var: usrout

- debug:
    var: usrout.name

- debug:
    var: usrout.comment
