---

all:

  hosts:

    # add the 1st instance
    web1:
      ansible_host: 54.164.163.195
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/Downloads/aws.pem

    # add the 2nd instance
    web2:
      ansible_host: 3.88.65.195
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/Downloads/aws.pem

    # add the 3rd instance
    db1:
      ansible_host: 54.224.0.55
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/Downloads/aws.pem

  children:
    webservers:
      hosts:
        web1:
        web2:
    dbservers:
      hosts:
        db1:
    allServers:
      children:
        webservers:
        dbservers: