# 
#  @author      : 00xWolf
#    GitHub    : @mmsaeed509
#    Developer : Mahmoud Mohamed
#     Copyright : Mahmoud Mohamed
#

apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
  - port: 15672
    targetPort: vpromq01-port
    protocol: TCP
  selector:
    app: vpromq01
  type: ClusterIP
