Vagrant.configure("2") do |config|

    # The 1st VM Ubuntu #
    config.vm.define "ubuntuVM1" do |ubuntuVM1|
      ubuntuVM1.vm.box = "ubuntu/jammy64"
      ubuntuVM1.vm.hostname = "ubuntuVM1"
      ubuntuVM1.vm.network "private_network", ip: "192.168.56.14"
    end

    # The 2nd VM CentOS #
    config.vm.define "centOSVM2Mariadb" do |centOSVM2Mariadb|
      centOSVM2Mariadb.vm.box = "eurolinux-vagrant/centos-stream-9"
      centOSVM2Mariadb.vm.hostname = "centOSVM2Mariadb"
      centOSVM2Mariadb.vm.network "private_network", ip: "192.168.56.20"
      centOSVM2Mariadb.vm.provision "shell", inline: <<-SHELL
        yum install -y wget unzip mariadb-server -y
        systemctl start mariadb
        systemctl enable mariadb
        # Additional provisioning steps for centOSVM2Mariadb
      SHELL
    end
  end
  