# 
#  @author      : 00xWolf
#    GitHub    : @mmsaeed509
#    Developer : Mahmoud Mohamed
#     Copyright : Mahmoud Mohamed
#

apiVersion: v1
kind: Pod
metadata:
  name: vpromc
  labels:
    app: vpromc
spec:
  containers:
  - name: vpromc
    image: memcached
    ports:
    - name: vpromc-port
      containerPort: 11211

